package at.aau.serg.websocketbrokerdemo

object GameConstants {
    const val PHASE_LOBBY = "LOBBY"
    const val PHASE_MINIGAME = "MINIGAME"
    const val COMMAND_FINISH_MINIGAME = "FINISH_MINIGAME"
    const val COMMAND_START_MINIGAME = "START_MINIGAME"
    const val COMMAND_ANNOUNCE_MINIGAME_RESULT = "ANNOUNCE_MINIGAME_RESULT"
    const val COMMAND_SUBMIT_GUESS = "SUBMIT_GUESS"
    const val COMMAND_USE_FREE_PASS = "USE_FREE_PASS"

    const val COMMAND_REACTION_READY = "REACTION_READY"
    const val COMMAND_REACTION_PRESS = "REACTION_PRESS"
    const val COMMAND_USE_SHAKE_CHEAT = "USE_SHAKE_CHEAT"
    const val COMMAND_REPORT_CHEAT = "REPORT_CHEAT"
}